*** About Me

I am a Computer Science Ph.D. student at The University of Georgia, USA, under the supervision of Dr. In Kee Kim. I received my B.S. in Computer Science at Universitas Amikom Yogyakarta, Indonesia, advised by Dr. Arief Setyanto. My research interests include Edge Computing, AI on Edge, and Internet of Things.  

You can find my CV [[file:../public/static/resume.pdf][here]]

*Office*\\
Boyd Graduate Studies Research Center\\
Room 819\\
200 D.W. Brooks Drive\\
Athens, GA, USA\\
30602

*Contact*\\
rakandhiya [dot] rachmanto [at] uga [dot] edu

*** Publications

#+ATTR_HTML: :class publications
- [[https://ieeexplore.ieee.org/document/10646443][Characterizing deep learning model compression with post-training quantization on accelerated edge devices]]
  - _Rakandhiya D Rachmanto_, Zaki Sukma, Ahmad NL Nabhaan, Arief Setyanto, Ting Jiang, In Kee Kim.
  - /IEEE EDGE 2024/
- [[https://ieeexplore.ieee.org/abstract/document/10852314][Knowledge Distillation in Object Detection for Resource-Constrained Edge Computing]]
  - Arief Setyanto, Theopilus Bayu Sasongko, Muhammad Ainul Fikri, Dhani Ariatmanto, I Made Artha Agastya, _Rakandhiya Daanii Rachmanto_, Affan Ardana, In Kee Kim
  - /IEEE Access 2025/

*** Teaching Assistant
- CSCI 4730/6730 (Operating Systems) /Fall 2025/
- CSCI 4050 (Software Engineering) /Fall 2025/

*** Other Interests
- Homelab: I enjoy building and maintaining my own stack of IT infrastructure, on NixOS, btw
- Lisp: I like trying out Lisp dialects (currently Clojure and Janet) because of how unique and elegant they are.
